-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kith'ix", {
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kith'ix", {
})
