local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("PetsCMID") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Vendor Pets\\Cappy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Ritual Site Pets\\Chubs")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Drop Pets\\Curious Lynx Kitten")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Achievement Pets\\Do, Child of Filo")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Gortham")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Princess Bloodshed")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Drop Pets\\Wriggling Capybara")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Dragonhawk Munchkin")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Achievement Pets\\Furiostraza")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Ritual Site Pets\\Rescued Dragonhawk Chick")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Flying Pets\\Dropped Pets\\Void-Scarred Eaglet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Humanoid Pets\\Achievement Pets\\Lil'Kruul")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Humanoid Pets\\Promotion Pets\\Murk'atath")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Vendor Pets\\Lil' Preyseeker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Vendor Pets\\Void-Infused Mindbreaker Fry")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Mechanical Pets\\Vendor Pets\\Preyhunter's Prismguard")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Mechanical Pets\\Vendor Pets\\Preyhunter's Riftbreaker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Akiki")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Akil Fledgling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Amber Treeflitter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Assistant Botanist Leafy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Autumn Snapling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Azure Sporebat")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Blistercreepling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Profession Pets\\Bubbly Snapling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Caustic Writhling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Corrosive Writhling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Cursed Spawn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Dali")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Devouring Runt")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Dragonhawk Mosswing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Ebon Snapling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Emberwing Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Emerald Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Fidoficus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Flicker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Gloom Toad")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Hexed Bunny")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Hawkstrider Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Jaundiced Slitherer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Kreepah'zoyd")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Drop Pets\\Lil' Mon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Linda the Lucky")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Lost Star")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Luma")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Mud Potadpole")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Naloki")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Nether Familiar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Nether Siphoner")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Nibblesworth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Achievement Pets\\Niblet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Nightfur Kapara")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Ominous Domanus")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Pangolil")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Percival")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Poisoned Parasite")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Riftblade Familiar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Rootling Nester")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Treasure Pets\\Scruffbeak")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Silkcrawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Silvermoon Broom")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Sleek Snakebiter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Snek'zali")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Achievement Pets\\Sootpaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Sporbie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Spormilian")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Steady Croakfrog")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Striped Snakebiter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Sunwing Hatchling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Swamp Biter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Treja'saka")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Vibrant Manaling")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Violet Chick")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Voidcrawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Volatile Venomfang")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Voldy")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Aquatic Pets\\Zone Pets\\Waddles")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Willie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Wrathful Wyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Ziorg'pharon")
