local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("MountsCMID") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Arboreal Pseudoshell")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Amani Blessed Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Ancestral War Bear")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Blessed Amani Burrower")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Cerulean Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Crimson Silvermoon Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Quest Mounts\\Emerald Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Fierce Grimlynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Frenzied Shredclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Gilneas Loyalist's Rouncey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Insatiable Shredclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Lucent Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Prowling Shredclaw")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Pyrewood Rebel's Rouncey")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Quest Mounts\\Relinquished Scarlet Charger")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Rootstalker Grimlynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Skypaw Glimmerfur")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Spectral Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Untainted Grove Crawler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Achievement Mounts\\Vivacious Chloroceros")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Profession Mounts\\Void-Corrupted Lynx")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Vivid Chloroceros")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Void-Touched Hawkstrider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Witherbark Pango")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Witherbark Warbear Mother")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Amani Sharptalon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Amani Sunfeather")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Amani Windcaller")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\In-Game Shop Mounts\\Amberback Arboon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Arcanovoid Construct")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Ashes of Belo'ren")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Blackwater X-TREME Firework Rocket")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\In-Game Shop Mounts\\Blossomback Arboon")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Calamitous Carrion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Cerulean Sporeglider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Cobalt Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Comfy Bel'ameth Flying Quilt")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Comfy Silvermoon Flying Quilt")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Convalescent Carrion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Elven Arcane Guardian")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Fiery Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Puzzle Mounts\\Luminous Sporeglider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Quest Mounts\\Peridot Dragonhawk")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Ruddy Sporeglider")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Promotion Mounts\\Scorching Valor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Tenebrous Harrower")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Unbound Manawyrm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Vibrant Petalwing")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Vicious Snapvine")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Void-Corrupted Hex Eagle")
ZygorGuidesViewer:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Aquatic Mounts\\Trading Post Mounts\\Savage Crimson Battle Turtle")
