--localization file for english/United States
local L = LibStub("AceLocale-3.0"):NewLocale("EasyExperienceBar", "enUS", true)

L["Easy Experience Bar"] = true
L["Information"] = true
L["Played Time Text"] = true
L["Show Level time text"] = true
L["Session Time Text"] = true
L["Show current session time"] = true
L["Leveling Time & XP/Hour Text"] = true
L["Show an estimate of how long it takes to hit the next level"] = true
L["Completed & Rested Text"] = true
L["Show how much rested XP and XP from completed quests the character has"] = true
L["Show Bar at Max Level"] = true
L["Do not hide the bar on max level characters"] = true
L["Reset Session Time and XP/Hour on Reload UI"] = true
L["Do not retain stats after a /reload"] = true
L["Hide Default Experience Bar"] = true
L["Hides the standard XP bar"] = true
L["Lock Bar"] = true
L["Disables the click and drag to move function"] = true
L["Size"] = true
L["Adjust bar size"] = true
L["Font"] = true
L["Font Selector"] = true
L["Bar Texture"] = true
L["Selects the texture used for the bars"] = true
L["Level "] = true
L["Max Level"] = true
L["Leveling in:"]  = true
L["XP/Hour"] = true
L["Completed:"] = true
L["Reset Timers"] = true
L["Resets Session and Level time"] = true
L["Rested:"] = true
L["Time played:"] = true
L["Time this level:"] = true
L["Time this session:"] = true
L["Completed Quest XP Bar"] = true
L["Show a bar indicating how much XP is available from completed quests"] = true
L["Text Outline"] = true
L["Adds a black outline to text"] = true
L["None"] = true
L["Outline"] = true
L["Thick Outline"] = true
L["Display"] = true
L["Settings"] = true
L["Width"] = true
L["Adjust bar width"] = true
L["Height"] = true
L["Adjust bar height"] = true
L["Font Size"] = true
L["Adjust font size"] = true
L["Use Class Color"] = true
L["Uses the player's class color for the progress bar"] = true
L['Advanced'] = true
L["FrameStrata"] = true
L["Sets the Frame Level for the bar (can be used to prevent the bar from hiding 'behind' other UI elements)"] = true
L["Background"] = true
L["Low"] = true
L["Medium"] = true
L["High"] = true
L["Dialog"] = true
L["Reset Bar Position"] = true
L["Resets Bar back to it's default position"] = true


