-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Nek'zali the Soulcoiler", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("Nek'zali the Soulcoiler", {
})

BigWigs:AddColors("Entombed Sentinels", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("Entombed Sentinels", {
})

BigWigs:AddColors("Vashnik the Malignant", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("Vashnik the Malignant", {
})

BigWigs:AddColors("The Lost Explorers", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("The Lost Explorers", {
})

BigWigs:AddColors("Sszorak", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("Sszorak", {
})

BigWigs:AddColors("The Twin Fangs", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("The Twin Fangs", {
})

BigWigs:AddColors("The Bargained Crown", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("The Bargained Crown", {
})

BigWigs:AddColors("Ula'tek", {
	["berserk"] = "cyan",
})

BigWigs:AddSounds("Ula'tek", {
})
