local LSM = LibStub("LibSharedMedia-3.0")

-- register sounds
LSM:Register("sound", "Heartbeat Single", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\HeartbeatSingle.ogg")
LSM:Register("sound", "Batman Punch", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\BatmanPunch.ogg")
LSM:Register("sound", "Bike Horn", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\BikeHorn.ogg")
LSM:Register("sound", "Boxing Arena Gong", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\BoxingArenaSound.ogg")
LSM:Register("sound", "Bleat", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Bleat.ogg")
LSM:Register("sound", "Cartoon Hop", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\CartoonHop.ogg")
LSM:Register("sound", "Cat Meow", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\CatMeow2.ogg")
LSM:Register("sound", "Kitten Meow", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\KittenMeow.ogg")
LSM:Register("sound", "Robot Blip", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\RobotBlip.ogg")
LSM:Register("sound", "Sharp Punch", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\SharpPunch.ogg")
LSM:Register("sound", "Water Drop", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\WaterDrop.ogg")
LSM:Register("sound", "Air Horn", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\AirHorn.ogg")
LSM:Register("sound", "Applause", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Applause.ogg")
LSM:Register("sound", "Banana Peel Slip", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\BananaPeelSlip.ogg")
LSM:Register("sound", "Blast", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Blast.ogg")
LSM:Register("sound", "Cartoon Voice Baritone", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\CartoonVoiceBaritone.ogg")
LSM:Register("sound", "Cartoon Walking", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\CartoonWalking.ogg")
LSM:Register("sound", "Cow Mooing", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\CowMooing.ogg")
LSM:Register("sound", "Ringing Phone", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\RingingPhone.ogg")
LSM:Register("sound", "Roaring Lion", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\RoaringLion.ogg")
LSM:Register("sound", "Shotgun", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Shotgun.ogg")
LSM:Register("sound", "Squish Fart", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\SquishFart.ogg")
LSM:Register("sound", "Temple Bell", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\TempleBellHuge.ogg")
LSM:Register("sound", "Torch", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Torch.ogg")
LSM:Register("sound", "Warning Siren", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\WarningSiren.ogg")
LSM:Register("sound", "Lich King Apocalypse", 554003) -- Sound\Creature\LichKing\IC_Lich King_Special01.ogg
-- Sounds from freesound.org, see commits in WeakAuras for attributions
LSM:Register("sound", "Sheep Blerping", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\SheepBleat.ogg")
LSM:Register("sound", "Rooster Chicken Call", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\RoosterChickenCalls.ogg")
LSM:Register("sound", "Goat Bleeting", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\GoatBleating.ogg")
LSM:Register("sound", "Acoustic Guitar", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\AcousticGuitar.ogg")
LSM:Register("sound", "Synth Chord", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\SynthChord.ogg")
LSM:Register("sound", "Chicken Alarm", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\ChickenAlarm.ogg")
LSM:Register("sound", "Xylophone", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Xylophone.ogg")
LSM:Register("sound", "Drums", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Drums.ogg")
LSM:Register("sound", "Tada Fanfare", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\TadaFanfare.ogg")
LSM:Register("sound", "Squeaky Toy Short", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\SqueakyToyShort.ogg")
LSM:Register("sound", "Error Beep", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\ErrorBeep.ogg")
LSM:Register("sound", "Oh No", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\OhNo.ogg")
LSM:Register("sound", "Double Whoosh", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\DoubleWhoosh.ogg")
LSM:Register("sound", "Brass", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Brass.mp3")
LSM:Register("sound", "Glass", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Glass.mp3")

LSM:Register("sound", "Voice: Adds", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Adds.ogg")
LSM:Register("sound", "Voice: Boss", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Boss.ogg")
LSM:Register("sound", "Voice: Circle", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Circle.ogg")
LSM:Register("sound", "Voice: Cross", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Cross.ogg")
LSM:Register("sound", "Voice: Diamond", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Diamond.ogg")
LSM:Register("sound", "Voice: Don't Release", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\DontRelease.ogg")
LSM:Register("sound", "Voice: Empowered", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Empowered.ogg")
LSM:Register("sound", "Voice: Focus", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Focus.ogg")
LSM:Register("sound", "Voice: Idiot", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Idiot.ogg")
LSM:Register("sound", "Voice: Left", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Left.ogg")
LSM:Register("sound", "Voice: Moon", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Moon.ogg")
LSM:Register("sound", "Voice: Next", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Next.ogg")
LSM:Register("sound", "Voice: Portal", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Portal.ogg")
LSM:Register("sound", "Voice: Protected", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Protected.ogg")
LSM:Register("sound", "Voice: Release", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Release.ogg")
LSM:Register("sound", "Voice: Right", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Right.ogg")
LSM:Register("sound", "Voice: Run Away", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\RunAway.ogg")
LSM:Register("sound", "Voice: Skull", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Skull.ogg")
LSM:Register("sound", "Voice: Spread", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Spread.ogg")
LSM:Register("sound", "Voice: Square", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Square.ogg")
LSM:Register("sound", "Voice: Stack", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Stack.ogg")
LSM:Register("sound", "Voice: Star", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Star.ogg")
LSM:Register("sound", "Voice: Switch", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Switch.ogg")
LSM:Register("sound", "Voice: Taunt", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Taunt.ogg")
LSM:Register("sound", "Voice: Triangle", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Triangle.ogg")

LSM:Register("sound", "Aggro", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\aggro.ogg")
LSM:Register("sound", "Arrow Swoosh", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Arrow_swoosh.ogg")
LSM:Register("sound", "Bam", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\bam.ogg")
LSM:Register("sound", "Polar Bear", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\bear_polar.ogg")
LSM:Register("sound", "Big Kiss", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\bigkiss.ogg")
LSM:Register("sound", "Bite", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\BITE.ogg")
LSM:Register("sound", "Burp", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\burp4.ogg")
LSM:Register("sound", "Cat", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\cat2.ogg")
LSM:Register("sound", "Chant Major 2nd", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\chant2.ogg")
LSM:Register("sound", "Chant Minor 3rd", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\chant4.ogg")
LSM:Register("sound", "Chimes", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\chimes.ogg")
LSM:Register("sound", "Cookie Monster", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\cookie.ogg")
LSM:Register("sound", "Electrical Spark", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\ESPARK1.ogg")
LSM:Register("sound", "Fireball", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Fireball.ogg")
LSM:Register("sound", "Gasp", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Gasp.ogg")
LSM:Register("sound", "Heartbeat", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\heartbeat.ogg")
LSM:Register("sound", "Hiccup", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\hic3.ogg")
LSM:Register("sound", "Huh?", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\huh_1.ogg")
LSM:Register("sound", "Hurricane", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\hurricane.ogg")
LSM:Register("sound", "Hyena", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\hyena.ogg")
LSM:Register("sound", "Kaching", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\kaching.ogg")
LSM:Register("sound", "Moan", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\moan.ogg")
LSM:Register("sound", "Panther", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\panther1.ogg")
LSM:Register("sound", "Phone", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\phone.ogg")
LSM:Register("sound", "Punch", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\PUNCH.ogg")
LSM:Register("sound", "Rain", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\rainroof.ogg")
LSM:Register("sound", "Rocket", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\rocket.ogg")
LSM:Register("sound", "Ship's Whistle", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\shipswhistle.ogg")
LSM:Register("sound", "Gunshot", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\shot.ogg")
LSM:Register("sound", "Snake Attack", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\snakeatt.ogg")
LSM:Register("sound", "Sneeze", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\sneeze.ogg")
LSM:Register("sound", "Sonar", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\sonar.ogg")
LSM:Register("sound", "Splash", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\splash.ogg")
LSM:Register("sound", "Squeaky Toy", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\Squeakypig.ogg")
LSM:Register("sound", "Sword Ring", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\swordecho.ogg")
LSM:Register("sound", "Throwing Knife", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\throwknife.ogg")
LSM:Register("sound", "Thunder", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\thunder.ogg")
LSM:Register("sound", "Wicked Male Laugh", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\wickedmalelaugh1.ogg")
LSM:Register("sound", "Wilhelm Scream", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\wilhelm.ogg")
LSM:Register("sound", "Wicked Female Laugh", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\wlaugh.ogg")
LSM:Register("sound", "Wolf Howl", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\wolf5.ogg")
LSM:Register("sound", "Yeehaw", "Interface\\AddOns\\WeakAuras_SharedMedia\\Sounds\\yeehaw.ogg")


-- register options font
LSM:Register("font", "Fira Mono Medium", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraMono-Medium.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
-- Other Fira fonts
LSM:Register("font", "Fira Sans Black", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSans-Heavy.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Fira Sans Condensed Black", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSansCondensed-Heavy.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Fira Sans Condensed Medium", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSansCondensed-Medium.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Fira Sans Medium", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSans-Medium.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "PT Sans Narrow Regular", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\PTSansNarrow-Regular.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "PT Sans Narrow Bold", "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\PTSansNarrow-Bold.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)

-- register plain white border
LSM:Register("border", "Square Full White", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Square_FullWhite.tga]])

LSM:Register("statusbar", "Clean", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Statusbar_Clean]])
LSM:Register("statusbar", "Stripes", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Statusbar_Stripes]])
LSM:Register("statusbar", "Thick Stripes", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Statusbar_Stripes_Thick]])
LSM:Register("statusbar", "Thin Stripes", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Statusbar_Stripes_Thin]])
LSM:Register("border", "Drop Shadow", [[Interface\AddOns\WeakAuras_SharedMedia\Textures\Border_DropShadow]])

