local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if ZGV:DoMutex("AchievementsCMID") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Midnight Safari")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Eversong Woods Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Harandar Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Midnight Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Voidstorm Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Zul'Aman Glyph Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\A Bloody Song")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Eversong Woods: The Highest Peaks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Harandar: The Highest Peaks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Midnight Lore Hunter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Tallest Tree in the Forest")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Eversong Woods")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Harandar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Voidstorm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Zul'aman")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Voidstorm: The Highest Peaks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Zul'Aman: The Highest Peaks")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Old World Family Battler")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Family Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Aquatic Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Beast Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Critter Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Dragonkin Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Elemental Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Flying Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Humanoid Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Magic Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Mechanical Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Undead Battler of Outland")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Family Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Aquatic Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Beast Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Critter Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Dragonkin Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Elemental Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Flying Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Humanoid Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Magic Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Mechanical Battler of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Undead Battler of Cataclysm")
